server:
  port: 8080

spring:
  application:
    name: jobsphere-backend
  data:
    mongodb:
      uri: ${mongodb+srv://morlaramyaasri_db_user:Morlameena%402@jobspherecluster.blnpqcc.mongodb.net/jobsphere?appName=jobspherecluster}
      #In local, swtch below to uncomment and use
      #uri: ${MONGODB_URI:mongodb://localhost:27017/jobsphere}
